INSERT INTO public.ingredients (name, kcal_per_gram, carbohydrates_per_gram, proteins_per_gram, fats_per_gram, avg_weight, avg_price, img_url, allergy_id, intolerance_id, ingredient_category_id) VALUES
--frutta
('Mela', 0.052, 0.14, 0.003, 0.002, 150, 0.5, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Banana', 0.89, 0.23, 0.01, 0.003, 120, 0.20, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Arancia', 0.47, 0.12, 0.01, 0.002, 130, 0.25, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Pera', 0.57, 0.15, 0.01, 0.003, 140, 0.28, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Uva', 0.69, 0.18, 0.01, 0.003, 200, 0.50, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Pesca', 0.39, 0.09, 0.01, 0.003, 140, 0.30, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Kiwi', 0.61, 0.14, 0.02, 0.004, 100, 0.40, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Melone', 0.34, 0.08, 0.01, 0.002, 800, 0.60, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Ananas', 0.50, 0.13, 0.01, 0.002, 300, 0.75, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Fragola', 0.32, 0.08, 0.01, 0.003, 50, 0.20, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Cocomero', 0.30, 0.08, 0.01, 0.02, 200, 1.2, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Clementine', 0.43, 0.12, 0.01, 0.02, 200, 0.6, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Fico', 0.74, 0.19, 0.01, 0.01, 50, 1.5, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Mango', 0.60, 0.15, 0.01, 0.02, 200, 2.5, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Papaya', 0.43, 0.11, 0.01, 0.02, 200, 1.2, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Lime', 0.29, 0.1, 0.01, 0.0, 50, 0.8, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Avocado', 1.6, 0.09, 0.02, 0.15, 150, 1.50, 'avocado.jpg', NULL, NULL,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),
('Limone', 0.29, 0.09, 0.01, 0.01, 120, 0.30, 'limone.jpg', NULL, NULL,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta')),

--verdura
('Pomodoro', 0.18, 0.04, 0.01, 0.003, 150, 0.20, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Cipolla', 0.40, 0.09, 0.01, 0.01, 100, 0.15, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Cipolla rossa', 0.4, 0.09, 0.02, 0.01, 100, 0.6, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Cipolla bianca', 0.4, 0.09, 0.02, 0.01, 100, 0.6, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Zucchina', 0.17, 0.03, 0.01, 0.004, 100, 0.10, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Carota', 0.41, 0.10, 0.01, 0.02, 80, 0.25, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Spinaci', 0.23, 0.04, 0.03, 0.003, 40, 0.30, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Lattuga', 0.15, 0.03, 0.01, 0.002, 60, 0.20, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Peperone', 0.31, 0.07, 0.01, 0.01, 100, 0.35, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Melanzana', 0.25, 0.06, 0.01, 0.01, 100, 0.20, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Broccoli', 0.34, 0.07, 0.03, 0.04, 150, 0.40, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Cavolfiore', 0.25, 0.05, 0.02, 0.02, 150, 0.30, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Cavolo', 0.25, 0.05, 0.02, 0.02, 100, 0.40, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Cavolo nero', 0.28, 0.06, 0.03, 0.02, 200, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Porro', 0.3, 0.07, 0.02, 0.01, 100, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Finocchio', 0.31, 0.07, 0.02, 0.01, 100, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Cavoletti di Bruxelles', 0.43, 0.09, 0.04, 0.02, 200, 1.1, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Patata', 0.77, 0.17, 0.02, 0.01, 150, 0.20, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Aglio', 1.49, 0.33, 0.06, 0.01, 10, 0.05, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Fagiolini', 0.31, 0.07, 0.02, 0.03, 100, 0.35, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Scalogno', 0.4, 0.09, 0.02, 0.01, 50, 0.3, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Patate dolci', 0.86, 0.20, 0.02, 0.05, 200, 1.2, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Carciofi', 0.47, 0.11, 0.02, 0.03, 100, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Asparagi', 0.2, 0.04, 0.02, 0.02, 100, 0.8, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Funghi champignon', 0.22, 0.05, 0.03, 0.01, 100, 0.6, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Cetriolo', 0.16, 0.04, 0.01, 0.01, 150, 0.40, 'cetriolo.jpg', NULL, NULL,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),
('Sedano', 0.16, 0.04, 0.01, 0.01, 100, 0.30, 'sedano.jpg', NULL, NULL,
(SELECT id FROM public.ingredient_categories WHERE name = 'verdura')),

--legumi
('Fagioli cannellini', 0.33, 0.58, 0.02, 0.01, 100, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'legumi')),
('Fagioli borlotti', 0.34, 0.59, 0.02, 0.02, 100, 1.1, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'legumi')),
('Fagioli rossi', 0.34, 0.61, 0.02, 0.02, 100, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'legumi')),
('Piselli', 0.81, 0.15, 0.05, 0.02, 100, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'legumi')),
('Lenticchie', 0.36, 0.63, 0.03, 0.02, 100, 1.1, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'legumi')),
('Ceci', 0.27, 0.45, 0.05, 0.02, 100, 0.50, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'legumi')),
('Fagioli neri', 0.35, 0.63, 0.02, 0.02, 100, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'legumi')),
('Soia', 0.44, 0.13, 0.03, 0.02, 100, 1.2, null,
(SELECT id FROM allergies WHERE name = 'Soia'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'legumi')),

--cereali
('Riso', 3.65, 0.77, 0.07, 0.02, 100, 0.30, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Riso basmati', 3.6, 0.75, 0.07, 0.02, 100, 1.1, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Riso integrale', 3.5, 0.75, 0.08, 0.02, 100, 1.2, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Pasta', 3.57, 0.71, 0.12, 0.01, 80, 1.00, 'pasta.jpg',
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Spaghetti', 3.5, 0.73, 0.12, 0.02, 100, 0.8, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Penne', 3.6, 0.74, 0.12, 0.03, 100, 0.9, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Fusilli', 3.5, 0.75, 0.13, 0.02, 100, 1.0, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Linguine', 3.6, 0.73, 0.12, 0.03, 100, 0.85, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Tagliatelle', 3.7, 0.76, 0.13, 0.03, 100, 1.1, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Maccheroni', 3.8, 0.77, 0.13, 0.03, 100, 0.95, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Orecchiette', 3.6, 0.73, 0.12, 0.02, 100, 1.2, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Gnocchi', 3.3, 0.7, 0.12, 0.02, 100, 1.2, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Farina', 3.64, 0.76, 0.08, 0.01, 100, 0.20, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Farina di riso', 3.6, 0.8, 0.06, 0.1, 100, 1.0, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Farina di mais', 3.5, 0.7, 0.06, 0.1, 100, 1.2, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Orzo', 3.33, 0.72, 0.06, 0.01, 100, 0.25, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Mais', 3.60, 0.74, 0.07, 0.02, 100, 0.30, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Avena', 3.89, 0.66, 0.14, 0.07, 100, 0.35, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Grano', 3.62, 0.76, 0.08, 0.01, 100, 0.30, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Segale', 3.49, 0.75, 0.09, 0.02, 100, 0.40, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Quinoa', 3.60, 0.64, 0.14, 0.06, 100, 0.55, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Bulgur', 3.50, 0.72, 0.12, 0.01, 100, 0.45, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Farro', 3.4, 0.70, 0.12, 0.03, 100, 1.5, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),
('Cous cous', 3.6, 0.72, 0.12, 0.02, 100, 1.4, null,
(SELECT id FROM allergies WHERE name = 'Glutine'),
(SELECT id FROM intolerances WHERE name = 'Glutine'),
(SELECT id FROM public.ingredient_categories WHERE name = 'cereali')),

--pesce
('Salmone', 1.96, 0.00, 0.25, 0.13, 150, 3.50, null,
(SELECT id FROM allergies WHERE name = 'Pesce'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'pesce')),
('Tonno', 1.60, 0.00, 0.23, 0.11, 150, 2.80, null,
(SELECT id FROM allergies WHERE name = 'Pesce'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'pesce')),
('Merluzzo', 1.20, 0.00, 0.20, 0.02, 150, 2.00, null,
(SELECT id FROM allergies WHERE name = 'Pesce'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'pesce')),
('Sardine', 2.40, 0.00, 0.25, 0.14, 120, 2.50, null,
(SELECT id FROM allergies WHERE name = 'Pesce'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'pesce')),
('Trota', 1.80, 0.00, 0.20, 0.12, 150, 2.20, null,
(SELECT id FROM allergies WHERE name = 'Pesce'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'pesce')),
('Gamberi', 1.60, 0.00, 0.20, 0.14, 100, 3.00, null,
(SELECT id FROM allergies WHERE name = 'Crostacei'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'pesce')),
('Granchio', 1.70, 0.00, 0.19, 0.13, 100, 3.20, null,
(SELECT id FROM allergies WHERE name = 'Crostacei'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'pesce')),
('Baccalà', 1.30, 0.00, 0.22, 0.03, 150, 2.60, null,
(SELECT id FROM allergies WHERE name = 'Pesce'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'pesce')),

--carne
('Carne di manzo', 2.50, 0.00, 0.20, 0.20, 200, 5.00, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'carne')),
('Carne di pollo', 2.00, 0.00, 0.30, 0.10, 200, 4.00, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'carne')),
('Carne di maiale', 2.40, 0.00, 0.25, 0.15, 200, 4.50, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'carne')),
('Agnello', 2.70, 0.00, 0.22, 0.18, 200, 5.20, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'carne')),
('Tacchino', 1.90, 0.00, 0.30, 0.05, 200, 4.00, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'carne')),
('Vitello', 2.30, 0.00, 0.20, 0.18, 200, 5.00, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'carne')),
('Prosciutto cotto', 1.30, 0.00, 0.18, 0.05, 50, 2.50, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'carne')),
('Salame', 2.90, 0.00, 0.15, 0.23, 50, 3.00, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'carne')),
('Pancetta', 5.42, 0.1, 0.37, 0.43, 30, 1.50, 'pancetta.jpg', NULL, NULL,
(SELECT id FROM public.ingredient_categories WHERE name = 'carne')),
('Pollo', 1.65, 0, 0.31, 0.04, 200, 2.50, 'pollo.jpg', NULL, NULL,
(SELECT id FROM public.ingredient_categories WHERE name = 'carne')),

--latticini
('Parmigiano', 4.32, 0.00, 0.35, 0.29, 30, 0.70, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Mozzarella', 2.37, 0.00, 0.20, 0.17, 125, 1.00, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Caciocavallo', 4.05, 0.00, 0.30, 0.33, 50, 1.20, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Pecorino', 4.50, 0.00, 0.30, 0.35, 50, 1.50, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Ricotta', 1.46, 0.00, 0.09, 0.10, 100, 0.80, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Feta', 2.6, 0.4, 0.14, 0.21, 40, 2.0, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Crescenza', 1.9, 0.2, 0.12, 0.11, 200, 1.4, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Ricotta Salata', 4.2, 0.5, 0.30, 0.33, 30, 3.0, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Taleggio', 3.4, 0.3, 0.23, 0.28, 40, 2.4, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Yogurt', 0.61, 0.07, 0.04, 0.03, 125, 0.60, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Burro', 7.17, 0.01, 0.02, 0.81, 25, 0.60, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Latte', 0.64, 0.03, 0.04, 0.03, 100, 0.50, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Panna', 3.80, 0.02, 0.02, 0.40, 100, 0.80, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Mascarpone', 4.02, 0.25, 0.05, 0.43, 250, 2.50, 'mascarpone.jpg',
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),
('Yogurt Greco', 0.59, 0.04, 0.10, 0.04, 200, 1.50, 'yogurt_greco.jpg',
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'latticini')),

--frutta_secca_e_semi
('Cocco', 3.66, 0.15, 0.03, 0.33, 30, 1.00, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta_secca_e_semi')),
('Mandorle', 5.80, 0.20, 0.21, 0.49, 15, 2.00, null,
(SELECT id FROM allergies WHERE name = 'Frutta a guscio'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta_secca_e_semi')),
('Nocciole', 6.00, 0.17, 0.14, 0.57, 10, 2.20, null,
(SELECT id FROM allergies WHERE name = 'Frutta a guscio'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta_secca_e_semi')),
('Anacardi', 5.30, 0.30, 0.18, 0.44, 10, 2.50, null,
(SELECT id FROM allergies WHERE name = 'Frutta a guscio'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta_secca_e_semi')),
('Semi di girasole', 5.60, 0.23, 0.21, 0.49, 20, 1.80, null,
(SELECT id FROM allergies WHERE name = 'Sesamo'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta_secca_e_semi')),
('Semi di lino', 5.50, 0.29, 0.18, 0.42, 15, 2.00, null,
(SELECT id FROM allergies WHERE name = 'Sesamo'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta_secca_e_semi')),
('Semi di zucca', 5.30, 0.18, 0.23, 0.46, 20, 2.30, null,
(SELECT id FROM allergies WHERE name = 'Sesamo'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta_secca_e_semi')),
('Sesamo', 5.70, 0.23, 0.18, 0.48, 15, 2.10, null,
(SELECT id FROM allergies WHERE name = 'Sesamo'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta_secca_e_semi')),
('Chia', 5.40, 0.42, 0.17, 0.34, 20, 2.20, null,
(SELECT id FROM allergies WHERE name = 'Sesamo'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta_secca_e_semi')),
('Arachidi', 5.50, 0.16, 0.25, 0.49, 10, 2.30, null,
(SELECT id FROM allergies WHERE name = 'Frutta a guscio'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta_secca_e_semi')),
('Noci', 6.5, 0.14, 0.15, 0.6, 30, 3.0, null,
(SELECT id FROM allergies WHERE name = 'Frutta a guscio'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta_secca_e_semi')),
('Semi di chia', 4.9, 0.42, 0.17, 0.3, 30, 3.5, null,
(SELECT id FROM allergies WHERE name = 'Sesamo'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'frutta_secca_e_semi')),

--grassi_vegetali
('Olio d''oliva', 8.84, 0.00, 0.00, 0.99, 100, 1.50, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'grassi_vegetali')),
('Olio di cocco', 8.99, 0.00, 0.00, 1.00, 100, 2.00, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'grassi_vegetali')),
('Olio di semi di girasole', 8.55, 0.00, 0.00, 1.00, 100, 1.70, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'grassi_vegetali')),
('Burro di arachidi', 5.70, 0.20, 0.25, 0.48, 20, 2.00, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'grassi_vegetali')),
('Margarina', 7.00, 0.01, 0.01, 0.80, 100, 1.20, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'grassi_vegetali')),

--dolci_e_zuccheri
('Cioccolato fondente', 5.60, 0.40, 0.05, 0.33, 30, 2.50, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'dolci_e_zuccheri')),
('Zucchero', 4.00, 1.00, 0.00, 0.00, 100, 0.30, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'dolci_e_zuccheri')),
('Miele', 3.00, 0.82, 0.00, 0.00, 50, 1.00, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'dolci_e_zuccheri')),
('Sciroppo d''acero', 3.10, 0.80, 0.00, 0.00, 50, 1.20, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'dolci_e_zuccheri')),
('Zucchero di canna', 4.0, 1.0, 0.0, 0.0, 100, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'dolci_e_zuccheri')),
('Zucchero semolato', 4.0, 1.0, 0.0, 0.0, 100, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'dolci_e_zuccheri')),
('Savoiardo', 3.9, 0.8, 0.06, 0.04, 20, 1.20, 'savoiardi.jpg', NULL, NULL,
(SELECT id FROM public.ingredient_categories WHERE name = 'dolci_e_zuccheri')),
('Cacao in polvere', 3.6, 0.5, 0.2, 0.2, 5, 0.80, 'cacao.jpg', NULL, NULL,
(SELECT id FROM public.ingredient_categories WHERE name = 'dolci_e_zuccheri')),

--bevande
('Acqua', 0.00, 0.00, 0.00, 0.00, 1000, 0.00, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'bevande')),
('Aceto', 0.02, 0.00, 0.00, 0.00, 100, 0.05, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'bevande')),
('Aceto balsamico', 0.88, 0.17, 0.01, 0.02, 100, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'bevande')),
('Aceto di mele', 0.22, 0.05, 0.01, 0.0, 100, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'bevande')),
('Salsa di soia', 0.53, 0.08, 0.06, 0.02, 100, 1.2, null,
(SELECT id FROM allergies WHERE name = 'Soia'), null,
(SELECT id FROM public.ingredient_categories WHERE name = 'bevande')),
('Caffè', 0.02, 0.00, 0.00, 0.00, 100, 0.10, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'bevande')),
('Tè verde', 0.01, 0.00, 0.00, 0.00, 100, 0.12, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'bevande')),
('Latte di mandorle', 0.46, 0.05, 0.01, 0.02, 200, 1.00, null,
(SELECT id FROM allergies WHERE name = 'Latticini'),
(SELECT id FROM intolerances WHERE name = 'Lattosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'bevande')),
('Succo d''arancia', 0.45, 0.10, 0.01, 0.00, 250, 0.80, null, null,
(SELECT id FROM intolerances WHERE name = 'Fruttosio'),
(SELECT id FROM public.ingredient_categories WHERE name = 'bevande')),
('Latte di Cocco', 0.19, 0.03, 0.01, 0.17, 240, 2.00, 'latte_di_cocco.jpg', NULL, NULL,
(SELECT id FROM public.ingredient_categories WHERE name = 'bevande')),

--uova
('Uova', 1.43, 0.1, 0.12, 0.1, 50, 0.25, 'uova.jpg', NULL, NULL,
(SELECT id FROM public.ingredient_categories WHERE name = 'uova')),

--altro
('Cacao amaro', 3.7, 0.5, 0.2, 0.3, 50, 1.2, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Vaniglia', 3.0, 0.0, 0.0, 0.0, 10, 3.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Curry', 4.0, 0.7, 0.2, 0.2, 10, 2.5, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Pepe nero', 3.3, 0.6, 0.1, 0.2, 5, 2.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Sale', 0.0, 0.0, 0.0, 0.0, 1, 0.05, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Zafferano', 2.9, 0.6, 0.1, 0.1, 5, 5.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Alloro', 2.2, 0.5, 0.1, 0.1, 1, 0.7, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Timo', 2.0, 0.3, 0.1, 0.1, 1, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Prezzemolo', 0.22, 0.04, 0.02, 0.01, 1, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Basilico', 0.23, 0.04, 0.02, 0.01, 30, 0.5, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Rosmarino', 2.5, 0.4, 0.2, 0.2, 5, 1.5, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Maggiorana', 2.2, 0.3, 0.1, 0.1, 1, 1.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Salvia', 2.4, 0.5, 0.2, 0.2, 5, 1.2, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Menta', 0.8, 0.16, 0.07, 0.04, 30, 0.6, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Paprika', 4.0, 0.85, 0.11, 0.2, 5, 1.8, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Peperoncino', 4.0, 0.85, 0.11, 0.2, 5, 2.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Cumino', 3.8, 0.63, 0.18, 0.2, 5, 2.3, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Curcuma', 3.0, 0.64, 0.08, 0.2, 5, 1.5, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Cilantro', 1.1, 0.2, 0.1, 0.03, 30, 0.7, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Tamarindo', 2.8, 0.63, 0.07, 0.1, 10, 3.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Zenzero', 3.8, 0.8, 0.07, 0.4, 5, 2.0, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Coriandolo', 0.2, 0.05, 0.02, 0.01, 10, 1.2, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Origano', 1.0, 0.22, 0.05, 0.02, 5, 1.8, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Dragoncello', 1.0, 0.24, 0.05, 0.02, 5, 2.2, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro')),
('Amido di mais', 3.8, 0.85, 0.02, 0.0, 100, 1.5, null, null, null,
(SELECT id FROM public.ingredient_categories WHERE name = 'altro'));